# Generated by Django 3.2.7 on 2021-09-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='section_name',
        ),
    ]
