# Generated by Django 3.2.7 on 2021-09-29 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210930_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='student',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
